project:
  type: website
  output-dir: docs
    

website:
  google-analytics: "G-3ZQ33TPE3P"
  navbar:
    title: "sudo_masochist"
    #TODO: change to false and is possible to have a gif
    #logo: images/test_gig.gif
    right:
      #- about.qmd
      - icon: github
        href: https://github.com/sudo-masochist/
        target: _blank
      - icon: reddit
        href: https://www.reddit.com/user/sudo_masochist/
        target: _blank
format:
  html:
    css: styles.css
    theme:
      light: [litera]
      dark: [solar]
    highlight-style: a11y-dark
    mainfont: "Menlo"
    code-copy: true
    code-overflow: wrap
editor: visual

